title:  "馨予&跃华"
tagline: "记录我们的幸福"
description:
author:
  name: "跃华"
  # twitter: paululele

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Interesting Facts', file: 'facts.html'}
- {name: 'Learning Resources', file: 'resources.html'}
- {name: 'Sample Posts', file: 'sample-posts.html'}
- {name: 'Documentation', file: 'documentation.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

# social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
